### PR TITLE
Pass an implicit ActorRefFactory to service methods

### PR DESCRIPTION
**Pull request by pdalpra**

### CODE REVIEW

**Comment by bobTheBot-teads** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.teadstesting.tv/job/github-api-client_pr/3/

**Comment by gbougeard** [comment]
LGTM

**Comment by bobTheBot-teads** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.teadstesting.tv/job/github-api-client_pr/4/

**Comment by pdalpra** [comment]
retest this please

**Comment by pdalpra** [comment]
retest this please

**Comment by gbougeard** [comment]
retest this please

**Comment by bobTheBot-teads** [comment]
Test FAILed.

**Comment by gbougeard** [comment]
retest this please

**Comment by gbougeard** [comment]
@pdalpra can you rebase?

**Comment by bobTheBot-teads** [comment]
Test FAILed.

**Comment by gbougeard** [comment]
nevermind, I'll do it

**Comment by gbougeard** [comment]
duplicate of #10

**Pull request closed without merging**
