### PR TITLE
Remove useless JSON writes

### PR DESCRIPTION
**Pull request by pdalpra**
Most of them are just useless: people won't serialize the model as is, they will collect data from calls to the API, put it in their model and then serialize that model.

Also remove the tag handling part from `Repository`: this is too overly specific to our own usage to go into an generic Github API client.

### CODE REVIEW

**Comment by gbougeard** [comment]
I understand but this involves breaking changes in Codebase

**Comment by pdalpra** [comment]
The part about tags?
We can easily mitigate this the next time we upgrade ;)

**Comment by gbougeard** [comment]
The Writes part too ;)

**Comment by pdalpra** [comment]
There are only a few places where we write models from github-api-client as-is, and we probably shouldn't, as we need only a very small part of those models for the UI.

**Comment by pdalpra** [comment]
retest

**Comment by pdalpra** [comment]
LGTY ?

**Comment by gbougeard** [comment]
LGTM good for >= 0.5.0

**Pull request merged**
